import type { AssetType, AssetStatus, Position } from '@/lib/types'
import type { TransformerProfile, ExelonOpCo, EXELON_OPCOS } from '@/lib/types/utility'

export interface ExelonAsset {
  assetTag: string
  name: string
  type: AssetType
  subType: string
  opCo: string
  substationName: string
  position: Position
  voltageClassKV: number
  ratedMVA: number
  yearInstalled: number
  manufacturer: string
  model: string
  coolingType: string
  status: AssetStatus
  healthIndex: number
  loadFactor: number
  customersServed: number
  program?: string
  criticality: 'critical' | 'major' | 'standard'
  lastInspection?: string
  specs?: {
    oilVolumeLiters?: number
    weight?: number
    tapChangerType?: string
    bushingType?: string
    serialNumber?: string
  }
}

export const EXELON_ASSETS: ExelonAsset[] = [
  // === ComEd (Northern Illinois) ===
  {
    assetTag: 'COMED-TF-001',
    name: 'Crawford 345/138kV Auto-Transformer #1',
    type: 'power_transformer',
    subType: 'Auto-Transformer',
    opCo: 'ComEd',
    substationName: 'Crawford Substation',
    position: { lat: 41.8219, lng: -87.6907 },
    voltageClassKV: 345,
    ratedMVA: 500,
    yearInstalled: 1978,
    manufacturer: 'GE',
    model: 'GE-500MVA-345',
    coolingType: 'OFAF',
    status: 'operational',
    healthIndex: 52,
    loadFactor: 78,
    customersServed: 85000,
    program: 'Grid Modernization',
    criticality: 'critical',
    lastInspection: '2025-08-15',
    specs: {
      oilVolumeLiters: 75000,
      weight: 220000,
      tapChangerType: 'OLTC',
      bushingType: 'OIP',
      serialNumber: 'GE-1978-CR-001',
    },
  },
  {
    assetTag: 'COMED-TF-002',
    name: 'Waukegan 138/34.5kV Transformer #2',
    type: 'power_transformer',
    subType: 'Step-Down Transformer',
    opCo: 'ComEd',
    substationName: 'Waukegan Substation',
    position: { lat: 42.3636, lng: -87.8448 },
    voltageClassKV: 138,
    ratedMVA: 84,
    yearInstalled: 1992,
    manufacturer: 'ABB',
    model: 'ABB-TRAX-84',
    coolingType: 'ONAF',
    status: 'operational',
    healthIndex: 71,
    loadFactor: 62,
    customersServed: 42000,
    program: 'Storm Hardening',
    criticality: 'major',
    lastInspection: '2025-11-03',
    specs: {
      oilVolumeLiters: 28000,
      weight: 95000,
      tapChangerType: 'OLTC',
      bushingType: 'RIP',
      serialNumber: 'ABB-1992-WK-002',
    },
  },
  {
    assetTag: 'COMED-TF-003',
    name: 'Lombard 138/12.47kV Distribution Transformer',
    type: 'distribution_transformer',
    subType: 'Distribution Substation Transformer',
    opCo: 'ComEd',
    substationName: 'Lombard Distribution Center',
    position: { lat: 41.8800, lng: -88.0078 },
    voltageClassKV: 138,
    ratedMVA: 28,
    yearInstalled: 2005,
    manufacturer: 'Siemens',
    model: 'SIE-TRBS-28',
    coolingType: 'ONAN',
    status: 'operational',
    healthIndex: 82,
    loadFactor: 55,
    customersServed: 18000,
    criticality: 'standard',
    lastInspection: '2025-09-22',
  },
  {
    assetTag: 'COMED-SS-001',
    name: 'Fisk Substation',
    type: 'substation',
    subType: 'Transmission Substation',
    opCo: 'ComEd',
    substationName: 'Fisk Substation',
    position: { lat: 41.8391, lng: -87.6554 },
    voltageClassKV: 345,
    ratedMVA: 1200,
    yearInstalled: 1965,
    manufacturer: 'Various',
    model: 'Multi-Bay',
    coolingType: 'N/A',
    status: 'operational',
    healthIndex: 58,
    loadFactor: 72,
    customersServed: 150000,
    program: 'Grid Modernization',
    criticality: 'critical',
  },
  {
    assetTag: 'COMED-TF-004',
    name: 'Electric Junction 345/138kV Transformer #3',
    type: 'power_transformer',
    subType: 'Auto-Transformer',
    opCo: 'ComEd',
    substationName: 'Electric Junction',
    position: { lat: 41.7500, lng: -87.6400 },
    voltageClassKV: 345,
    ratedMVA: 448,
    yearInstalled: 1985,
    manufacturer: 'Westinghouse',
    model: 'WH-448MVA-345',
    coolingType: 'OFAF',
    status: 'maintenance',
    healthIndex: 44,
    loadFactor: 0,
    customersServed: 65000,
    program: 'Transformer Replacement',
    criticality: 'critical',
    lastInspection: '2025-12-01',
    specs: {
      oilVolumeLiters: 68000,
      weight: 195000,
      tapChangerType: 'OLTC',
      bushingType: 'OIP',
      serialNumber: 'WH-1985-EJ-003',
    },
  },

  // === PECO (Southeastern Pennsylvania) ===
  {
    assetTag: 'PECO-TF-001',
    name: 'Plymouth Meeting 230/69kV Transformer #1',
    type: 'power_transformer',
    subType: 'Step-Down Transformer',
    opCo: 'PECO',
    substationName: 'Plymouth Meeting Substation',
    position: { lat: 40.1020, lng: -75.2740 },
    voltageClassKV: 230,
    ratedMVA: 200,
    yearInstalled: 1988,
    manufacturer: 'ABB',
    model: 'ABB-TRAX-200',
    coolingType: 'ONAF',
    status: 'operational',
    healthIndex: 61,
    loadFactor: 71,
    customersServed: 55000,
    program: 'Capacity Expansion',
    criticality: 'critical',
    lastInspection: '2025-07-18',
    specs: {
      oilVolumeLiters: 42000,
      weight: 145000,
      tapChangerType: 'OLTC',
      bushingType: 'OIP',
      serialNumber: 'ABB-1988-PM-001',
    },
  },
  {
    assetTag: 'PECO-TF-002',
    name: 'Eddystone 230/69kV Transformer #2',
    type: 'power_transformer',
    subType: 'Step-Down Transformer',
    opCo: 'PECO',
    substationName: 'Eddystone Substation',
    position: { lat: 39.8581, lng: -75.3255 },
    voltageClassKV: 230,
    ratedMVA: 168,
    yearInstalled: 1995,
    manufacturer: 'Hitachi Energy',
    model: 'HE-168MVA-230',
    coolingType: 'ONAF',
    status: 'operational',
    healthIndex: 74,
    loadFactor: 58,
    customersServed: 38000,
    criticality: 'major',
    lastInspection: '2025-10-10',
  },
  {
    assetTag: 'PECO-TF-003',
    name: 'Whitpain 69/13.2kV Distribution Transformer',
    type: 'distribution_transformer',
    subType: 'Distribution Substation Transformer',
    opCo: 'PECO',
    substationName: 'Whitpain Substation',
    position: { lat: 40.1530, lng: -75.2770 },
    voltageClassKV: 69,
    ratedMVA: 33,
    yearInstalled: 2010,
    manufacturer: 'Siemens',
    model: 'SIE-TRBS-33',
    coolingType: 'ONAN',
    status: 'operational',
    healthIndex: 88,
    loadFactor: 48,
    customersServed: 15000,
    criticality: 'standard',
  },

  // === BGE (Central Maryland) ===
  {
    assetTag: 'BGE-TF-001',
    name: 'Westport 230/115kV Auto-Transformer #1',
    type: 'power_transformer',
    subType: 'Auto-Transformer',
    opCo: 'BGE',
    substationName: 'Westport Substation',
    position: { lat: 39.2632, lng: -76.6260 },
    voltageClassKV: 230,
    ratedMVA: 336,
    yearInstalled: 1974,
    manufacturer: 'GE',
    model: 'GE-336MVA-230',
    coolingType: 'OFAF',
    status: 'alert',
    healthIndex: 38,
    loadFactor: 82,
    customersServed: 72000,
    program: 'Transformer Replacement',
    criticality: 'critical',
    lastInspection: '2025-12-20',
    specs: {
      oilVolumeLiters: 55000,
      weight: 178000,
      tapChangerType: 'OLTC',
      bushingType: 'OIP',
      serialNumber: 'GE-1974-WP-001',
    },
  },
  {
    assetTag: 'BGE-TF-002',
    name: 'Riverside 115/34.5kV Transformer #3',
    type: 'power_transformer',
    subType: 'Step-Down Transformer',
    opCo: 'BGE',
    substationName: 'Riverside Substation',
    position: { lat: 39.3200, lng: -76.5800 },
    voltageClassKV: 115,
    ratedMVA: 100,
    yearInstalled: 1999,
    manufacturer: 'ABB',
    model: 'ABB-TRAX-100',
    coolingType: 'ONAF',
    status: 'operational',
    healthIndex: 69,
    loadFactor: 65,
    customersServed: 35000,
    criticality: 'major',
    lastInspection: '2025-09-05',
  },
  {
    assetTag: 'BGE-SS-001',
    name: 'Canton Substation',
    type: 'substation',
    subType: 'Distribution Substation',
    opCo: 'BGE',
    substationName: 'Canton Substation',
    position: { lat: 39.2818, lng: -76.5783 },
    voltageClassKV: 115,
    ratedMVA: 400,
    yearInstalled: 1982,
    manufacturer: 'Various',
    model: 'Multi-Bay',
    coolingType: 'N/A',
    status: 'operational',
    healthIndex: 63,
    loadFactor: 70,
    customersServed: 45000,
    program: 'Storm Hardening',
    criticality: 'major',
  },
  {
    assetTag: 'BGE-TF-003',
    name: 'Calvert Cliffs 500/230kV Transformer #1',
    type: 'power_transformer',
    subType: 'Generator Step-Up',
    opCo: 'BGE',
    substationName: 'Calvert Cliffs Switchyard',
    position: { lat: 38.4320, lng: -76.4420 },
    voltageClassKV: 500,
    ratedMVA: 700,
    yearInstalled: 1975,
    manufacturer: 'Westinghouse',
    model: 'WH-700MVA-500',
    coolingType: 'ODAF',
    status: 'operational',
    healthIndex: 55,
    loadFactor: 88,
    customersServed: 120000,
    program: 'Grid Modernization',
    criticality: 'critical',
    specs: {
      oilVolumeLiters: 95000,
      weight: 310000,
      tapChangerType: 'DETC',
      bushingType: 'OIP',
      serialNumber: 'WH-1975-CC-001',
    },
  },

  // === Pepco (Washington D.C. & suburban Maryland) ===
  {
    assetTag: 'PEPCO-TF-001',
    name: 'Benning Road 230/69kV Transformer #2',
    type: 'power_transformer',
    subType: 'Step-Down Transformer',
    opCo: 'Pepco',
    substationName: 'Benning Road Substation',
    position: { lat: 38.8950, lng: -76.9560 },
    voltageClassKV: 230,
    ratedMVA: 224,
    yearInstalled: 1981,
    manufacturer: 'GE',
    model: 'GE-224MVA-230',
    coolingType: 'ONAF',
    status: 'operational',
    healthIndex: 48,
    loadFactor: 76,
    customersServed: 62000,
    program: 'Transformer Replacement',
    criticality: 'critical',
    lastInspection: '2025-11-12',
    specs: {
      oilVolumeLiters: 48000,
      weight: 155000,
      tapChangerType: 'OLTC',
      bushingType: 'OIP',
      serialNumber: 'GE-1981-BR-002',
    },
  },
  {
    assetTag: 'PEPCO-TF-002',
    name: 'Takoma 69/13.8kV Distribution Transformer',
    type: 'distribution_transformer',
    subType: 'Distribution Substation Transformer',
    opCo: 'Pepco',
    substationName: 'Takoma Substation',
    position: { lat: 38.9778, lng: -77.0074 },
    voltageClassKV: 69,
    ratedMVA: 28,
    yearInstalled: 2012,
    manufacturer: 'Hitachi Energy',
    model: 'HE-28MVA-69',
    coolingType: 'ONAN',
    status: 'operational',
    healthIndex: 91,
    loadFactor: 42,
    customersServed: 12000,
    criticality: 'standard',
  },
  {
    assetTag: 'PEPCO-SS-001',
    name: 'Capitol Hill Substation',
    type: 'substation',
    subType: 'Underground Network',
    opCo: 'Pepco',
    substationName: 'Capitol Hill Substation',
    position: { lat: 38.8899, lng: -76.9820 },
    voltageClassKV: 69,
    ratedMVA: 300,
    yearInstalled: 1970,
    manufacturer: 'Various',
    model: 'Underground Network',
    coolingType: 'N/A',
    status: 'operational',
    healthIndex: 56,
    loadFactor: 68,
    customersServed: 80000,
    program: 'Grid Modernization',
    criticality: 'critical',
  },

  // === Delmarva Power (Delaware & Eastern Shore MD) ===
  {
    assetTag: 'DPL-TF-001',
    name: 'Indian River 230/69kV Transformer #1',
    type: 'power_transformer',
    subType: 'Step-Down Transformer',
    opCo: 'DPL',
    substationName: 'Indian River Substation',
    position: { lat: 38.6120, lng: -75.0620 },
    voltageClassKV: 230,
    ratedMVA: 150,
    yearInstalled: 1990,
    manufacturer: 'ABB',
    model: 'ABB-TRAX-150',
    coolingType: 'ONAF',
    status: 'operational',
    healthIndex: 66,
    loadFactor: 60,
    customersServed: 48000,
    program: 'Capacity Expansion',
    criticality: 'major',
    lastInspection: '2025-06-30',
  },
  {
    assetTag: 'DPL-TF-002',
    name: 'Edge Moor 138/69kV Auto-Transformer',
    type: 'power_transformer',
    subType: 'Auto-Transformer',
    opCo: 'DPL',
    substationName: 'Edge Moor Substation',
    position: { lat: 39.7470, lng: -75.5130 },
    voltageClassKV: 138,
    ratedMVA: 112,
    yearInstalled: 1997,
    manufacturer: 'Siemens',
    model: 'SIE-112MVA-138',
    coolingType: 'ONAF',
    status: 'operational',
    healthIndex: 73,
    loadFactor: 54,
    customersServed: 31000,
    criticality: 'major',
  },

  // === Atlantic City Electric (Southern New Jersey) ===
  {
    assetTag: 'ACE-TF-001',
    name: 'Cardiff 230/69kV Transformer #1',
    type: 'power_transformer',
    subType: 'Step-Down Transformer',
    opCo: 'ACE',
    substationName: 'Cardiff Substation',
    position: { lat: 39.4070, lng: -74.5400 },
    voltageClassKV: 230,
    ratedMVA: 180,
    yearInstalled: 1986,
    manufacturer: 'GE',
    model: 'GE-180MVA-230',
    coolingType: 'ONAF',
    status: 'operational',
    healthIndex: 58,
    loadFactor: 67,
    customersServed: 52000,
    program: 'Storm Hardening',
    criticality: 'critical',
    lastInspection: '2025-10-25',
    specs: {
      oilVolumeLiters: 38000,
      weight: 130000,
      tapChangerType: 'OLTC',
      bushingType: 'OIP',
      serialNumber: 'GE-1986-CF-001',
    },
  },
  {
    assetTag: 'ACE-TF-002',
    name: 'Oyster Creek 69/13.2kV Distribution Transformer',
    type: 'distribution_transformer',
    subType: 'Distribution Substation Transformer',
    opCo: 'ACE',
    substationName: 'Oyster Creek Substation',
    position: { lat: 39.8130, lng: -74.2050 },
    voltageClassKV: 69,
    ratedMVA: 25,
    yearInstalled: 2015,
    manufacturer: 'Hitachi Energy',
    model: 'HE-25MVA-69',
    coolingType: 'ONAN',
    status: 'operational',
    healthIndex: 92,
    loadFactor: 38,
    customersServed: 11000,
    criticality: 'standard',
  },
  {
    assetTag: 'ACE-SS-001',
    name: 'Lewis Substation',
    type: 'substation',
    subType: 'Transmission Substation',
    opCo: 'ACE',
    substationName: 'Lewis Substation',
    position: { lat: 39.4615, lng: -74.6335 },
    voltageClassKV: 230,
    ratedMVA: 600,
    yearInstalled: 1979,
    manufacturer: 'Various',
    model: 'Multi-Bay',
    coolingType: 'N/A',
    status: 'operational',
    healthIndex: 60,
    loadFactor: 64,
    customersServed: 95000,
    program: 'Storm Hardening',
    criticality: 'critical',
  },
]

export function getExelonAssetByTag(assetTag: string): ExelonAsset | undefined {
  return EXELON_ASSETS.find(a => a.assetTag === assetTag)
}

export function getAssetsByOpCo(opCo: string): ExelonAsset[] {
  return EXELON_ASSETS.filter(a => a.opCo === opCo)
}

export function getAssetsByType(type: AssetType): ExelonAsset[] {
  return EXELON_ASSETS.filter(a => a.type === type)
}

export function getCriticalAssets(): ExelonAsset[] {
  return EXELON_ASSETS.filter(a => a.criticality === 'critical')
}

export function getAgingAssets(thresholdYears: number = 35): ExelonAsset[] {
  const currentYear = new Date().getFullYear()
  return EXELON_ASSETS.filter(a => (currentYear - a.yearInstalled) >= thresholdYears)
}

